/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import org.example.Conversao.conversorFahrenheit;
import org.example.Conversao.conversorCelsius;

class AppTest {

    @Test
    void conversaoCelsius() {

        conversorCelsius celsius = new conversorCelsius();

        String result = celsius.conversao(20);
        String expected = "Conversão para Fahrenheit: 68,00";
        assertEquals(expected, result);
    }

    @Test
    void conversaoFahrenheit() {

        conversorFahrenheit fahrenheit = new conversorFahrenheit();

        String result = fahrenheit.conversao(20);
        String expected = "Conversão para Celsius: -6,67";
        assertEquals(expected, result);
    }
}
